/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <ButtonMatrix01_1_API.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <ButtonMatrix01_1_BM_A.h>
#include <ButtonMatrix01_1_BM_A_aliases.h>
#include <ButtonMatrix01_1_BM_1.h>
#include <ButtonMatrix01_1_BM_1_aliases.h>
#include <ButtonMatrix01_1_BM_2.h>
#include <ButtonMatrix01_1_BM_2_aliases.h>
#include <ButtonMatrix01_1_BM_3.h>
#include <ButtonMatrix01_1_BM_3_aliases.h>
#include <ButtonMatrix01_1_BM_4.h>
#include <ButtonMatrix01_1_BM_4_aliases.h>
#include <ButtonMatrix01_1_BM_B.h>
#include <ButtonMatrix01_1_BM_B_aliases.h>
#include <ButtonMatrix01_1_BM_C.h>
#include <ButtonMatrix01_1_BM_C_aliases.h>
#include <ButtonMatrix01_1_ISR_A.h>
#include <ButtonMatrix01_1_ISR_B.h>
#include <ButtonMatrix01_1_ISR_C.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

